# Generated by Django 4.2.15 on 2024-09-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
