# Generated by Django 4.2.15 on 2024-09-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
