# Generated by Django 4.2.16 on 2024-10-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_price_orderdetail_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
