# Generated by Django 4.2.16 on 2024-10-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_orderdetail_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
