# Generated by Django 4.2.16 on 2024-10-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_product_taxable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='taxable',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
