# Generated by Django 4.2.16 on 2024-10-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_orderdetail_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
