# Generated by Django 4.2.16 on 2024-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_orderdetail_product_orderdetail_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
