# Generated by Django 4.2.16 on 2024-10-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_orderdetail_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_price',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
    ]
