# Generated by Django 4.2.16 on 2024-10-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_orderdetail_product_orderdetail_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='taxable',
        ),
    ]
